name: ruff

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: "ruff"
    steps:
      - uses: davidslusser/actions_python_ruff@v1.0.1
        with:
          pip_install_command: "pip install -r requirements-nox.txt"
          python_version: "3.11"



